// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/canimcp"
)

// NewMockDetector creates a new instance of MockDetector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDetector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDetector {
	mock := &MockDetector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDetector is an autogenerated mock type for the Detector type
type MockDetector struct {
	mock.Mock
}

type MockDetector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDetector) EXPECT() *MockDetector_Expecter {
	return &MockDetector_Expecter{mock: &_m.Mock}
}

// Match provides a mock function for the type MockDetector
func (_mock *MockDetector) Match(req canimcp.Evidence) (canimcp.HostType, canimcp.AuthMethod) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Match")
	}

	var r0 canimcp.HostType
	var r1 canimcp.AuthMethod
	if returnFunc, ok := ret.Get(0).(func(canimcp.Evidence) (canimcp.HostType, canimcp.AuthMethod)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(canimcp.Evidence) canimcp.HostType); ok {
		r0 = returnFunc(req)
	} else {
		r0 = ret.Get(0).(canimcp.HostType)
	}
	if returnFunc, ok := ret.Get(1).(func(canimcp.Evidence) canimcp.AuthMethod); ok {
		r1 = returnFunc(req)
	} else {
		r1 = ret.Get(1).(canimcp.AuthMethod)
	}
	return r0, r1
}

// MockDetector_Match_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Match'
type MockDetector_Match_Call struct {
	*mock.Call
}

// Match is a helper method to define mock.On call
//   - req canimcp.Evidence
func (_e *MockDetector_Expecter) Match(req any) *MockDetector_Match_Call {
	return &MockDetector_Match_Call{Call: _e.mock.On("Match", req)}
}

func (_c *MockDetector_Match_Call) Run(run func(req canimcp.Evidence)) *MockDetector_Match_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 canimcp.Evidence
		if args[0] != nil {
			arg0 = args[0].(canimcp.Evidence)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDetector_Match_Call) Return(hostType canimcp.HostType, authMethod canimcp.AuthMethod) *MockDetector_Match_Call {
	_c.Call.Return(hostType, authMethod)
	return _c
}

func (_c *MockDetector_Match_Call) RunAndReturn(run func(req canimcp.Evidence) (canimcp.HostType, canimcp.AuthMethod)) *MockDetector_Match_Call {
	_c.Call.Return(run)
	return _c
}
